name:                 obsidian-graph
version:              0.1.0.0
visibility:           public
id:                   obsidian-graph-0.1.0.0-inplace
key:                  obsidian-graph-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    Clusters GraphBuilder Metrics Neighbors Parser Paths Pretty Types
    Visualization

import-dirs:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/dist-newstyle/build/aarch64-osx/ghc-9.6.7/obsidian-graph-0.1.0.0/build

library-dirs:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/dist-newstyle/build/aarch64-osx/ghc-9.6.7/obsidian-graph-0.1.0.0/build

library-dirs-static:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/dist-newstyle/build/aarch64-osx/ghc-9.6.7/obsidian-graph-0.1.0.0/build

dynamic-library-dirs:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/dist-newstyle/build/aarch64-osx/ghc-9.6.7/obsidian-graph-0.1.0.0/build

data-dir:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/.

hs-libraries:         HSobsidian-graph-0.1.0.0-inplace
depends:
    base-4.18.3.0 containers-0.6.7 directory-1.3.8.5 filepath-1.4.301.0
    process-1.6.19.0

haddock-interfaces:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/dist-newstyle/build/aarch64-osx/ghc-9.6.7/obsidian-graph-0.1.0.0/doc/html/obsidian-graph/obsidian-graph.haddock

haddock-html:
    /Users/benjaminheim/Documents/func_prog/assignments/final-project-bheim/dist-newstyle/build/aarch64-osx/ghc-9.6.7/obsidian-graph-0.1.0.0/doc/html/obsidian-graph
